# Generated by Django 4.2.6 on 2023-11-03 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, verbose_name='Название товара')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('quant', models.FloatField(verbose_name='Масса/Кол-во')),
                ('amount', models.FloatField(verbose_name='Сумма')),
                ('create_db', models.DateField(auto_now_add=True, verbose_name='Дата покупки')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='purchases.category', to_field='slug', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Наименование покупки',
                'verbose_name_plural': 'Покупки',
                'ordering': ('category', 'name'),
            },
        ),
    ]
