# Generated by Django 4.2.6 on 2023-12-04 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('period', models.DurationField(blank=True, help_text='Выберите промежуток времени', null=True, verbose_name='Промежуток времени')),
                ('time', models.DateTimeField(blank=True, help_text='Выберите время проведения', null=True, verbose_name='Дата и время проведения')),
                ('description', models.TextField(blank=True, help_text='Добавьте описание к событию', null=True, verbose_name='Описание')),
            ],
        ),
    ]
