# Generated by Django 4.2.6 on 2023-12-20 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('time',), 'verbose_name': 'Событие', 'verbose_name_plural': 'События'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='period',
        ),
    ]
